seeder:
  file: ./seeder/seeder.rb
  disabled: false
parsers:
  - file: ./parsers/listings.rb
    page_type: listings
    disabled: false
  - page_type: details
    file: ./parsers/details.rb
    disabled: false
exporters:
  - file: ./exporters/products_last10_json.yaml
    disabled: false
  - file: ./exporters/products_json.yaml
    disabled: false
finisher:
  file: ./finisher/finisher.rb
  disabled: false