exporter_name: products_csv
exporter_type: csv
collection: products
start_on_job_done: true
fields:
  - header: "gid"
    path: "_gid"
  - header: "created_at"
    path: "_created_at"
  - header: "price"
    path: "price"
  - header: "feedback"
    path: "feedback"
  - header: "seller"
    path: "seller"